# Generated by Django 4.2.11 on 2024-03-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField(unique=True)),
                ('spotify_access_token', models.CharField(max_length=255)),
                ('spotify_refresh_token', models.CharField(max_length=255)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
